### ISSUE TITLE
ID 73bb5308-d754-4ef2-b058-6b1b90e4cc8c

### ISSUE THREAD

**Issue by salvatoregnazzi** [neodyme-labs/solana-security-txt#39]
ID 73bb5308-d754-4ef2-b058-6b1b90e4cc8c
  Wallet:0xe4025DF65DdF62Bcf234e186484c7302D20FE121@43114

_Originally posted by @Johnson1s in https://github.com/neodyme-labs/solana-security-txt/issues/7#issuecomment-1935132755_

**Comment by salvatoregnazzi** [comment]
> ```
>           ID 73bb5308-d754-4ef2-b058-6b1b90e4cc8c
> ```
> 
> Wallet:0xe4025DF65DdF62Bcf234e186484c7302D20FE121@43114
> 
> _Originally posted by @Johnson1s in [#7 (comment)](https://github.com/neodyme-labs/solana-security-txt/issues/7#issuecomment-1935132755)_

**Comment by bitdude24** [comment]
Duplicate of #141

**Comment by aleksola** [comment]
> ```
>           ID 73bb5308-d754-4ef2-b058-6b1b90e4cc8c
> ```
> 
> Wallet:0xe4025DF65DdF62Bcf234e186484c7302D20FE121@43114
> 
> _Originally posted by [@Johnson1s](https://github.com/Johnson1s) in [#7 (comment)](https://github.com/neodyme-labs/solana-security-txt/issues/7#issuecomment-1935132755)_
