### ISSUE TITLE
Reducing the security.txt size by using a serialisation protocol instead and Improvement Suggestions

### ISSUE THREAD

**Issue by mryalamanchi** [neodyme-labs/solana-security-txt#6]
Currently, the .security.txt takes away quite some bytes to store the information,
since everything originially is in string format.

What could be done to further improve this is using a serialisation protocol, 
preferably borsch, to serialise the entire security.txt key:value pairs. 

- Each **pre-defined key** is an **unsigned 1-byte integer**, giving use upto 255 keys to use.
e.g., name - 0x01,  project_url - 0x02, etc.

- Now, to identify the HEADER and FOOTER we use 
a 6 byte magic number to indentify the same.

  HEADER = 0xDEC1A551F1ED (hex-word play on Declassified)
  FOOTER = 0xEDF151A5C1DE (little-endian byte swap (HEADER))

  `HEADER + serialised security.txt + FOOTER`

- For the `encryption` key part, having PGP makes total sense to communicate securely with the contract dev.
Just not sure about an external link so much. Finality of the pgp public key as a string 
with the recently deployed code makes more sense. 
Default recommendation to the dev can be to provide the PGP public key!

**Note**: For any upgradeable smart contract on Solana 
the change in the spec of security.txt doesn't effect the eBPF bytecode exec, 
or anything for the smart contract devs.

Although a minimum coordination may be requied with the 
Explorer services that are using this.
 
Would love to hear you thoughts on this @CherryWorm!

**Comment by tlambertz** [comment]
Thanks for the suggestions :)

We opted for a string-only format to make this format easy to parse. Even without a parser, you can just look at the raw binary and see the security.txt. If we'd drop this requirement, one could even think about compressing it with gzip or something.


It would be possible to save a few bytes here and there, but I'm not sure its worth it. A hello world anchor program is already huge, a few bytes more won't change things much.

Is the size a big concern for you? A short security.txt containing just a name, the project url, a couple of contacts and a sone sentence policy (or link to one) fits easily in 300 bytes including headers, which costs ~0.002 SOL, or ~$0.20 with the current SOL price. Compared to the cost of deploying a program, often 1-10 SOL, this seems negligible.

Explorer support was written by us as well, would be easy to change.

**Comment by mryalamanchi** [comment]
I agree with the parser becoming easy to make, since it's decode and then pattern search!

But having a something like a borsch serialise and deserialise is not that hard to have IMO!
The developer anyway isn't going to customise the security.text with additional fields.

So space optimisation is definitely something I am looking forward to!
But, gzip is a pretty good option!

I leaning more toward serialisation!

**Comment by mryalamanchi** [comment]
If not serialisation gzip would be good anyway!
Let me push a PR and see if it's fine with you guys.

**Comment by mryalamanchi** [comment]
Was the reason to stick with string was that ELF secion extraction is a bit too much on javascript and rust client?

**Comment by tlambertz** [comment]
I like the current approach, since it is [KISS](https://en.wikipedia.org/wiki/KISS_principle).

For example, it does not require a single dependency. Especially when writing smart contracts, you should consider all dependencies carefully, as each one might introduce a security issue (eg if the developer is compromised). By having none, you just don't have to think about it.

It's of course possible to do compile-time gzip, but saving just a couple of bytes is not worth the complexity and drawbacks in other areas.

Also, we've already been asked to add support for contracts written in C (though we have not implemented it yet), so any changes should work there as well. For example, there is currently no borsh implementation for C, so using borsh here would require awkward workarounds for non-rust contracts.

**Comment by mryalamanchi** [comment]
On a second thought, I think my comment was "premature-optimisation" for storage. 
I was recently reminded that such compression may expose it to a zip bomb like vuln on the decode/extract on the client sides or other ones that may introduce any non-determinism.

Also, in future, if the SOL Progs are possible to be written in different langauges, it just introduces unnecessary lib dependencies.

I wondered if it can be abstracted away in the anchor framework, as an issue to add support for security.txt has already been added there. But it looks unnecessary to introduce such a change for few bytes and makes changes everywhere else to reflect!

And yes, for the C contracts adding gzip will be another pain point during compilation.

I will close this issue now because it's premature.

I appreciate your time, thank you.
